
settest:
	civl verify -userIncludePath=../../include \
          -inputkind=0 -inputnthreads=2 -inputsteps_bound=3 schedtest.cvl schedule.cvl

queuetest:
	civl verify -userIncludePath=../../include \
          -inputkind=1 -inputnthreads=2 -inputsteps_bound=3 schedtest.cvl schedule.cvl

pqueuetest:
	civl verify -userIncludePath=../../include \
          -inputkind=2 -inputnthreads=2 -inputsteps_bound=3 schedtest.cvl schedule.cvl
