//returns: (counts[0] + ,,, counts[n-1])! / counts[0]! , *** counts[n-1]!
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>

void printPerm(int idx_perms, int size_perm, int** perms){
    printf("Perm[%d]:\t", idx_perms);
    for (int j = 0; j < size_perm; j++){
        printf("%d, ", perms[idx_perms][j]);
    }
    printf("\n");
}

void printPerms(int num_perms, int size_perm, int** perms){
    for (int i = 0; i < num_perms; i++){
        printf("Perm[%d]:\t", i);
        for (int j = 0; j < size_perm; j++){
            printf("%d ", perms[i][j]);
        }
        printf("\n");
    }
}

/*  Factorial(n) */
int fact(int n){
  int result = 1;
	
  for (int i = 1; i <= n; i++){
    result *= i;
  }
  return result;
}

/* Computes the number of permutations generated by the counts array */
int calc_num_perms(int n, int * counts){
  int sum = 0;
	
  for (int i = 0; i < n; i++){
    sum += counts[i];
  }
  int numerator = fact(sum);
	
  int denom = 1;
  for (int i = 0; i < n; i++){
    denom *= fact(counts[i]);
  }
	
  return numerator/denom;
}

// ignore
int* create_perm_array(int n, int* counts, int* perm_array, int a, int indx, int count){
	
  for (int i = a; i < n; i++){
    if(counts[i] > 1 && count == 0){
      perm_array[i] += i;
      indx++;
      count++;
      counts[i] -= 1;
      create_perm_array(n, counts, perm_array, a, indx, count);
    }
    else if(counts[i] > 1 && count != 0){
      perm_array[count] += i;
      indx++;
      count++;
      counts[i] -= 1;
      create_perm_array(n, counts, perm_array, a, indx, count);
    }
    else if(counts[i] <= 1 && count > 0){
      perm_array[count] = i;
      indx++;
      counts[i] += count;
      count=0;
      create_perm_array(n, counts, perm_array, (a+1), indx, count);
    }
    else {
      perm_array[indx] += i;
      indx++;
    }
  }
  return perm_array;
}

void perm_aux(int **table,
	      int i0,
	      int j0,
	      int len,
	      int * counts) {
  for (int i=0; i<len; i++) {
    if (counts[i] != 0) {
      int new_counts[len];
      for (int j=0; j<len; j++) {
	new_counts[j] = j==i ? counts[j]-1 : counts[j];
      }
      int np = calc_num_perms(len, new_counts);
      for (int j=0; j<np; j++) {
	table[i0+j][j0] = i;
      }
      perm_aux(table, i0, j0+1, len, new_counts);
      i0 += np;
    }
  }
}

/* Computes the permutations generated by counts array */
int** compute_perms(int n, int * counts){
  int num_rows = calc_num_perms(n, counts);
  int sum = 0;
  for (int i = 0; i < n; i++){
    sum += counts[i];
  }
  int num_cols = sum;
  int** result = malloc(num_rows * sizeof(int*));
  for (int i = 0; i < num_rows; i++){
    result[i] = malloc(num_cols * sizeof(int));
  }
  perm_aux(result, 0, 0, n, counts);
  return result;
}

/* Linearizability check, returns false if the next op to be added has a start time
   that is earlier than some other op that has already been added to the permuation.*/
_Bool check_times(int* row,
		  int curr_total_op_count,
		  int tid_next,
		  int stp_b,
		  int start_times[][stp_b],
		  int nthreads) {
  int curr_op_counts[nthreads];
  int counts_index[nthreads];
  for (int i = 0; i < nthreads; i++) {
    curr_op_counts[i] = 0;
    counts_index[i] = 0;
  }
  for (int i = 0; i < curr_total_op_count - 1; i++) {
    curr_op_counts[row[i]]++;
  }  
  int next_start_time = start_times[tid_next][curr_op_counts[tid_next]];
  for (int i = 0; i < curr_total_op_count - 1; i++) {
    if (next_start_time < start_times[row[i]][curr_op_counts[counts_index[row[i]]++]]) {
      printf("Time check failed.\n");
      printf("Next start time: %d\n", next_start_time);
      printf("Later start time already inserted: %d\n",
	     start_times[row[i]][curr_op_counts[counts_index[row[i]]-1]]);
      printf("Total op count before current insertion: %d\n", curr_total_op_count - 1);
      return false;
    }
  }
  return true;
}

/* Analogous to perm_aux but includes linearizability check */
void linearizable_aux(int **table,
		      int i0,
		      int j0,
		      int nthreads,
		      int * counts,
		      int stp_b,
		      int start_times[][stp_b]) {
  for (int i=0; i<nthreads; i++) {
    if (counts[i] != 0) {
      int new_counts[nthreads];
      for (int j=0; j<nthreads; j++) {
	new_counts[j] = j==i ? counts[j]-1 : counts[j];
      }
      int np = calc_num_perms(nthreads, new_counts);
      for (int j=0; j<np; j++) {
	if (table[i0+j][0] >= 0) {
	  if (check_times(table[i0+j], j0, i, stp_b, start_times, nthreads)) {
	    table[i0+j][j0] = i;
	  } else {
	    table[i0+j][0] = -1;
	  }
	}
      }
      linearizable_aux(table, i0, j0+1, nthreads, new_counts, stp_b, start_times);
      i0 += np;
    }
  }  
}

/* Computes the permutations generated by counts array, filtering out
   permuations that fail to meet the linearizability condition. Filtered
   perms are flagged with a -1 in their first index. */
int** compute_linearizable_perms(int n, int* counts, int stp_b, int start_times[][stp_b]) {
  int num_rows = calc_num_perms(n, counts);
  int sum = 0;
  for (int i = 0; i < n; i++) {
    sum += counts[i];
  }
  int num_cols = sum;
  int** result = (int **) malloc(num_rows * sizeof(int*));
  for (int i = 0; i < num_rows; i++) {
    result[i] = (int *) malloc(num_cols * sizeof(int));
    for (int j = 0; j < num_cols; j++) {
      result[i][j] = 0;
    }
  }
  linearizable_aux(result, 0, 0, n, counts, stp_b, start_times);
  /*
    // Consider copying the old array into a new smaller array without
    // the trimmed perms?
    int** old_result = result;
    int new_num_rows = 0;
    for (int i = 0; i < num_rows; i++) {
    if (result[i][0] >= 0) new_num_rows++;
    }
  */
  return result;
}


void test_1(int n, int* counts){
  int sum = 0;
  int a = 0;
  int indx = 0;
  int count = 0;
	
  for (int i = 0; i < n; i++){
    sum += counts[i];
  }
	
  int* perm_array = malloc(sum * sizeof(int));
	
  perm_array = create_perm_array(n, counts, perm_array, a, indx, count);
  printf("create_perm_array(3, (2,1,1), perm_array, 0, 0, 0) = %d\n", *perm_array);
}

/*
int main() {
  int test_n = 4;
  int* test_counts;
  test_counts = (int*) malloc(sizeof(int)*test_n);
  test_counts[0] = 1;
  test_counts[1] = 1;
  test_counts[2] = 2;
  test_counts[3] = 1;
  //test_1(test_n, test_counts);
  int** result = compute_perms(test_n, test_counts);
  int num_rows = calc_num_perms(test_n, test_counts);
  int num_cols = 0;
  for (int i = 0; i < test_n; i++) {
    num_cols += test_counts[i];
  }
  for (int i = 0; i < num_rows; i++) {
    for (int j = 0; j < num_cols; j++) {
      printf("%d ", result[i][j]);
    }
    printf("\n");
  }
  return 0;
}
*/
