#ifndef _PERM_H
#define _PERM_H
#include "schedule.h"

void perm_print(int idx_perms, int size_perm, int** perms);

void perm_print_all(int num_perms, int size_perm, int** perms);

/* Computes the number of permutations generated by the counts array */
int perm_calc_num(int n, int * counts);

/* Computes the permutations generated by counts array */
int** perm_compute(int n, int * counts);

/* Computes the permutations generated by counts array, filtering out
   permuations that fail to meet the linearizability condition. Filtered
   perms are flagged with a -1 in their first index. */
int** perm_compute_linear(int stp_b, schedule_t schedule);

#endif
